[2025-03-10T07:29:41.605+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T07:29:41.655+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_extract manual__2025-03-10T07:16:17.278383+00:00 [queued]>
[2025-03-10T07:29:41.924+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_extract manual__2025-03-10T07:16:17.278383+00:00 [queued]>
[2025-03-10T07:29:41.925+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-10T07:29:41.953+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_extract> on 2025-03-10 07:16:17.278383+00:00
[2025-03-10T07:29:41.968+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T07:29:41.971+0000] {standard_task_runner.py:72} INFO - Started process 75 to run task
[2025-03-10T07:29:41.971+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_orchestration_dag', 'trigger_extract', 'manual__2025-03-10T07:16:17.278383+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpeqzu7psy']
[2025-03-10T07:29:41.973+0000] {standard_task_runner.py:105} INFO - Job 317: Subtask trigger_extract
[2025-03-10T07:29:42.069+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_orchestration_dag.trigger_extract manual__2025-03-10T07:16:17.278383+00:00 [running]> on host c77555d100c4
[2025-03-10T07:29:42.214+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_orchestration_dag' AIRFLOW_CTX_TASK_ID='trigger_extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T07:16:17.278383+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T07:16:17.278383+00:00'
[2025-03-10T07:29:42.216+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T07:29:42.216+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T07:29:42.217+0000] {logging_mixin.py:190} INFO - Current task name:trigger_extract state:running start_date:2025-03-10 07:29:41.656745+00:00
[2025-03-10T07:29:42.217+0000] {logging_mixin.py:190} INFO - Dag name:tiki_orchestration_dag and current dag run status:running
[2025-03-10T07:29:42.218+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T07:29:42.330+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:30:42.362+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:31:42.370+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:32:42.379+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:33:42.390+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:34:42.397+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:35:42.402+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:36:42.407+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:37:42.413+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:38:42.420+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:39:42.430+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:40:42.439+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:41:42.460+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:42:42.476+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:43:42.495+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:44:42.524+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 07:29:42.218757+00:00 to become allowed state ['success'] ...
[2025-03-10T07:45:42.686+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_extract_dag failed with failed states failed
[2025-03-10T07:45:42.757+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T07:45:42.758+0000] {logging_mixin.py:190} INFO - Task start:2025-03-10 07:29:41.656745+00:00 end:2025-03-10 07:45:42.729093+00:00 duration:961.072348
[2025-03-10T07:45:42.763+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_extract> dag:<DAG: tiki_orchestration_dag> dagrun:<DagRun tiki_orchestration_dag @ 2025-03-10 07:16:17.278383+00:00: manual__2025-03-10T07:16:17.278383+00:00, state:running, queued_at: 2025-03-10 07:16:17.353718+00:00. externally triggered: True>
[2025-03-10T07:45:42.764+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_extract_dag failed with failed states failed
[2025-03-10T07:45:42.766+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_orchestration_dag, task_id=trigger_extract, run_id=manual__2025-03-10T07:16:17.278383+00:00, execution_date=20250310T071617, start_date=20250310T072941, end_date=20250310T074542
[2025-03-10T07:45:42.902+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T07:45:42.910+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 317 for task trigger_extract (tiki_extract_dag failed with failed states failed; 75)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_extract_dag failed with failed states failed
[2025-03-10T07:45:43.012+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T07:45:43.170+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T07:45:43.185+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
