[2025-03-09T10:18:45.702+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T10:18:45.737+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_extract_dag.extract_data manual__2025-03-09T10:18:40.659649+00:00 [queued]>
[2025-03-09T10:18:45.754+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_extract_dag.extract_data manual__2025-03-09T10:18:40.659649+00:00 [queued]>
[2025-03-09T10:18:45.755+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-09T10:18:45.785+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data> on 2025-03-09 10:18:40.659649+00:00
[2025-03-09T10:18:45.804+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T10:18:45.809+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2025-03-09T10:18:45.808+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_extract_dag', 'extract_data', 'manual__2025-03-09T10:18:40.659649+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/tiki_extract_dag.py', '--cfg-path', '/tmp/tmpmucd7rru']
[2025-03-09T10:18:45.811+0000] {standard_task_runner.py:105} INFO - Job 117: Subtask extract_data
[2025-03-09T10:18:45.913+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_extract_dag.extract_data manual__2025-03-09T10:18:40.659649+00:00 [running]> on host 4dc18dee7126
[2025-03-09T10:18:46.434+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_extract_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T10:18:40.659649+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T10:18:40.659649+00:00'
[2025-03-09T10:18:46.436+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T10:18:46.437+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T10:18:46.438+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2025-03-09 10:18:45.738738+00:00
[2025-03-09T10:18:46.439+0000] {logging_mixin.py:190} INFO - Dag name:tiki_extract_dag and current dag run status:running
[2025-03-09T10:18:46.443+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T10:18:46.472+0000] {tiki_extract_dag.py:22} INFO - Loaded categories: ['lam-dep-suc-khoe', 'dien-thoai-may-tinh-bang', 'laptop-may-vi-tinh-linh-kien', 'dien-gia-dung', 'sach', 'thiet-bi-kts-phu-kien-so', 'thoi-trang-nu', 'thoi-trang-nam', 'dong-ho-va-trang-suc', 'dien-tu-dien-lanh']
[2025-03-09T10:18:46.473+0000] {tiki_extract_dag.py:23} INFO - Execution date: 2025-03-09 10:18:40.659649+00:00
[2025-03-09T10:18:50.390+0000] {crawl_data.py:106} INFO - Crawling category lam-dep-suc-khoe with 10 pages
[2025-03-09T10:18:51.455+0000] {crawl_data.py:131} INFO - Extracted page 1 - lam-dep-suc-khoe, 40 items, total extracted: 40
[2025-03-09T10:18:56.738+0000] {crawl_data.py:131} INFO - Extracted page 2 - lam-dep-suc-khoe, 40 items, total extracted: 80
[2025-03-09T10:18:59.392+0000] {crawl_data.py:131} INFO - Extracted page 3 - lam-dep-suc-khoe, 40 items, total extracted: 120
[2025-03-09T10:19:04.079+0000] {crawl_data.py:131} INFO - Extracted page 4 - lam-dep-suc-khoe, 40 items, total extracted: 160
[2025-03-09T10:19:07.494+0000] {crawl_data.py:131} INFO - Extracted page 5 - lam-dep-suc-khoe, 40 items, total extracted: 200
[2025-03-09T10:19:11.536+0000] {crawl_data.py:131} INFO - Extracted page 6 - lam-dep-suc-khoe, 40 items, total extracted: 240
[2025-03-09T10:19:16.394+0000] {crawl_data.py:131} INFO - Extracted page 7 - lam-dep-suc-khoe, 40 items, total extracted: 280
[2025-03-09T10:19:19.912+0000] {crawl_data.py:131} INFO - Extracted page 8 - lam-dep-suc-khoe, 40 items, total extracted: 320
[2025-03-09T10:19:24.879+0000] {crawl_data.py:131} INFO - Extracted page 9 - lam-dep-suc-khoe, 40 items, total extracted: 360
[2025-03-09T10:19:31.226+0000] {crawl_data.py:131} INFO - Extracted page 10 - lam-dep-suc-khoe, 40 items, total extracted: 400
[2025-03-09T10:19:33.365+0000] {crawl_data.py:106} INFO - Crawling category dien-thoai-may-tinh-bang with 10 pages
[2025-03-09T10:19:34.766+0000] {crawl_data.py:131} INFO - Extracted page 1 - dien-thoai-may-tinh-bang, 40 items, total extracted: 440
[2025-03-09T10:19:41.287+0000] {crawl_data.py:131} INFO - Extracted page 2 - dien-thoai-may-tinh-bang, 40 items, total extracted: 480
[2025-03-09T10:19:46.099+0000] {crawl_data.py:131} INFO - Extracted page 3 - dien-thoai-may-tinh-bang, 40 items, total extracted: 520
[2025-03-09T10:19:58.684+0000] {crawl_data.py:131} INFO - Extracted page 4 - dien-thoai-may-tinh-bang, 40 items, total extracted: 560
[2025-03-09T10:20:38.570+0000] {crawl_data.py:134} ERROR - API error for page 5 - dien-thoai-may-tinh-bang: HTTPSConnectionPool(host='tiki.vn', port=443): Read timed out.
[2025-03-09T10:20:38.571+0000] {crawl_data.py:106} INFO - Crawling category laptop-may-vi-tinh-linh-kien with 10 pages
[2025-03-09T10:21:00.885+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=3, read=2, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='tiki.vn', port=443): Read timed out. (read timeout=15)")': /api/v2/products?page=1&category=1846&limit=50
[2025-03-09T10:21:09.514+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=2, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74fdc7a0>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=1846&limit=50
[2025-03-09T10:21:18.724+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74c1bd40>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=1846&limit=50
[2025-03-09T10:21:26.731+0000] {crawl_data.py:134} ERROR - API error for page 1 - laptop-may-vi-tinh-linh-kien: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products?page=1&category=1846&limit=50 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d75f666f0>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)"))
[2025-03-09T10:21:26.733+0000] {crawl_data.py:106} INFO - Crawling category dien-gia-dung with 10 pages
[2025-03-09T10:21:34.740+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74be1100>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=1882&limit=50
[2025-03-09T10:21:43.344+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74be3f20>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=1882&limit=50
[2025-03-09T10:21:52.553+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74be3ce0>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=1882&limit=50
[2025-03-09T10:22:00.559+0000] {crawl_data.py:134} ERROR - API error for page 1 - dien-gia-dung: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products?page=1&category=1882&limit=50 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74be3a10>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)"))
[2025-03-09T10:22:00.561+0000] {crawl_data.py:106} INFO - Crawling category sach with 10 pages
[2025-03-09T10:22:08.569+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d7502ba10>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=8322&limit=50
[2025-03-09T10:22:17.174+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d746dd700>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=8322&limit=50
[2025-03-09T10:22:26.382+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d746dda60>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=8322&limit=50
[2025-03-09T10:22:34.399+0000] {crawl_data.py:134} ERROR - API error for page 1 - sach: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products?page=1&category=8322&limit=50 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d746ddb80>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)"))
[2025-03-09T10:22:34.400+0000] {crawl_data.py:106} INFO - Crawling category thiet-bi-kts-phu-kien-so with 10 pages
[2025-03-09T10:22:42.405+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d746de240>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=1815&limit=50
[2025-03-09T10:22:51.015+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d748bbd10>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=1815&limit=50
[2025-03-09T10:22:55.249+0000] {crawl_data.py:131} INFO - Extracted page 1 - thiet-bi-kts-phu-kien-so, 40 items, total extracted: 600
[2025-03-09T10:23:22.531+0000] {crawl_data.py:134} ERROR - API error for page 2 - thiet-bi-kts-phu-kien-so: HTTPSConnectionPool(host='tiki.vn', port=443): Read timed out.
[2025-03-09T10:23:22.533+0000] {crawl_data.py:106} INFO - Crawling category thoi-trang-nu with 10 pages
[2025-03-09T10:23:30.541+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74bbfb60>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=931&limit=50
[2025-03-09T10:23:39.146+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74733e30>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=931&limit=50
[2025-03-09T10:23:48.354+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74734230>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=931&limit=50
[2025-03-09T10:23:56.362+0000] {crawl_data.py:134} ERROR - API error for page 1 - thoi-trang-nu: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products?page=1&category=931&limit=50 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74734500>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)"))
[2025-03-09T10:23:56.364+0000] {crawl_data.py:106} INFO - Crawling category thoi-trang-nam with 10 pages
[2025-03-09T10:24:04.372+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74734d70>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=915&limit=50
[2025-03-09T10:24:12.978+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74734e90>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=915&limit=50
[2025-03-09T10:24:22.188+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74733b00>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=915&limit=50
[2025-03-09T10:24:30.195+0000] {crawl_data.py:134} ERROR - API error for page 1 - thoi-trang-nam: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products?page=1&category=915&limit=50 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74733f50>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)"))
[2025-03-09T10:24:30.197+0000] {crawl_data.py:106} INFO - Crawling category dong-ho-va-trang-suc with 10 pages
[2025-03-09T10:24:38.204+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d747331a0>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=8371&limit=50
[2025-03-09T10:24:46.808+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74733830>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=8371&limit=50
[2025-03-09T10:24:56.017+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74733440>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=8371&limit=50
[2025-03-09T10:25:04.026+0000] {crawl_data.py:134} ERROR - API error for page 1 - dong-ho-va-trang-suc: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products?page=1&category=8371&limit=50 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74735040>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)"))
[2025-03-09T10:25:04.027+0000] {crawl_data.py:106} INFO - Crawling category dien-tu-dien-lanh with 10 pages
[2025-03-09T10:25:12.033+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74735280>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=4221&limit=50
[2025-03-09T10:25:20.641+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74735580>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=4221&limit=50
[2025-03-09T10:25:29.849+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74735760>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=1&category=4221&limit=50
[2025-03-09T10:25:37.856+0000] {crawl_data.py:134} ERROR - API error for page 1 - dien-tu-dien-lanh: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products?page=1&category=4221&limit=50 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74735880>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)"))
[2025-03-09T10:25:46.058+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8d74736510>: Failed to resolve 'oauth2.googleapis.com' ([Errno -3] Temporary failure in name resolution)")': /token
[2025-03-09T10:25:56.146+0000] {crawl_data.py:49} INFO - Updated crawled products at tiki-data/tiki_crawled/crawled_products.json
[2025-03-09T10:25:56.148+0000] {crawl_data.py:147} INFO - Uploaded raw data to tiki-data/tiki_raw_data/raw_20250309_102538.json, total items: 600
[2025-03-09T10:25:56.220+0000] {tiki_extract_dag.py:30} INFO - Extracted data and saved to tiki_raw_data/raw_20250309_102538.json
[2025-03-09T10:25:56.222+0000] {python.py:240} INFO - Done. Returned value was: tiki_raw_data/raw_20250309_102538.json
[2025-03-09T10:25:56.266+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T10:25:56.268+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=tiki_extract_dag, task_id=extract_data, run_id=manual__2025-03-09T10:18:40.659649+00:00, execution_date=20250309T101840, start_date=20250309T101845, end_date=20250309T102556
[2025-03-09T10:25:56.324+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-09T10:25:56.325+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-09T10:25:56.326+0000] {logging_mixin.py:190} INFO - Dag name:tiki_extract_dag queued_at:2025-03-09 10:18:40.723634+00:00
[2025-03-09T10:25:56.327+0000] {logging_mixin.py:190} INFO - Task hostname:4dc18dee7126 operator:PythonOperator
[2025-03-09T10:25:56.389+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-09T10:25:56.424+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T10:25:56.428+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
